{{- if empty .Values.existingSecrets }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "emhass.fullname" . }}
  labels:
    {{- include "emhass.labels" . | nindent 4 }}
data:
  secrets_emhass.yaml: |-
{{- if index (.Values.secrets) "secrets_emhass.yaml" }}
  {{- index (.Values.secrets) "secrets_emhass.yaml" | b64enc | nindent 4 -}}
{{- end }}
{{- end }}
